export const points = [
  "",
  "You had my super invested in fossil fuels.",
  "I believe the impact of fossil fuel investments in my super costs more than those investments are worth.",
  "My super isn’t just the money I retire with, it’s the world my investments create for when I get to retire.",
  "You did not disclose where you were investing my money, which leads me to believe this information reflects poorly on you.",
  "You did not invest in line with Paris Agreement goals or in a way that accounts for the urgency of the climate crisis.",
  "The investments you had my super in compromised my personal values and ethics.",
  "I have been personally affected by climate change and your investments were doing nothing to deal with this important issue.",
  "Clean energy is the future I want and need super to be invested in, and you compromised that future with fossil fuels.",
  "Divest from fossil fuels so that all your members are protected from the environmental harm being caused today and stranded assets in the future.",
  "Invest more in clean energy instead of fossil fuels so that super can contribute to a better future.",
  "Develop a sustainable ESG super option that excludes fossil fuels and alert your members so that they can choose not to finance pollution. ",
  "Make a commitment to exclude all fossil fuels by 2030.",
  "I expect a response, explaining the decisions you made with my money and why you haven’t acted sooner on climate change.",
  "I would like This email to be passed on to your Executives and management.",
]
